# file's extentions
ALLOWED_TRAINED_MODEL_FILE_EXTENSIONS = set(['joblib'])
ALLOWED_DATA_SET_FILE_EXTENSIONS = set(['csv'])
ALLOWED_FIELD_VALUES_FILE_EXTENSIONS = set(['csv'])

# reauest params
UPLOAD_TRAINED_MODEL_REQUEST_PARAM = 'trainedModel'
UPLOAD_TRAINED_MODEL_NAME_REQUEST_PARAM = 'trainedModelName'
DATA_SET_REQUEST_PARAM = 'dataSet'
MODEL_ID_REQUEST_PARAM = 'modelId'
TRAINING_TARGET_FEATURE_REQUEST_PARAM = 'target'
FIELD_VALUES_REQUEST_PARAMS = 'fieldValues'

# response fields
CONFUSION_MATRINX_TNR = 'trueNegative'
CONFUSION_MATRINX_FPR = 'falsePositive'
CONFUSION_MATRINX_FNR = 'falseNegative'
CONFUSION_MATRINX_TPR = 'truePositive'

CLASSIFICATION_PREDICTION_RESULT_VALUE = "value"
CLASSIFICATION_PREDICTION_RESULT_PROBABILITY = "probability"

# config
UPLOAD_FOLDER_CONFIG_PARAM = 'UPLOAD_FOLDER'
SQLALCHEMY_DATABASE_URI_CONFIG_PARAM = 'SQLALCHEMY_DATABASE_URI'

# testing dirictory 
DEFAULT_UPLOAD_PATH = 'D:\\trainedmodels'
DEFAULT_DB_DIRICTORY = 'sqlite:///D:\\trainedmodels\\hrmlp.db'
